name: k6 Load Test

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  k6-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Setup K6
        uses: grafana/setup-k6-action@v1.1.0

      - name: Run k6 test
        uses: grafana/run-k6-action@v1.1.3
        with:
          path: K6/test-plans/Blaze-demo-test.js